Feature/project refact
marocraft/trackntrace pull request #45
Opened 2019-05-16 13:41 UTC by housseine

2019-05-17 10:09 UTC, khalid-elabbadi approved these changes

2019-05-17 13:19 UTC, EggIt requested changes

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/build/DefaultLogBuilder.java
> +	@Qualifier("logtraceDefault")
use defaultLogTrace instead of logTraceDefault. this way, we'll have the same naming pattern
The same applies for other qualifiers

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/config/ConfigurationTnTDefault.java
> +	@Value("${tnt.logging.format.default}")
logging key should have the groupid prefix to avoid conflicts with user defined props

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/domain/LogTraceDefault.java
> +public class LogTraceDefault implements ILogTrace {
If LogTraceDefault is a POJO then replace ILogTrace with a base class instead.

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/domain/LogTraceRest.java
> +public class LogTraceRest implements ILogTrace {
If LogTraceRest is a POJO then replace ILogTrace with a base class instead.

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/http/Correlater.java
> +	@Value(value="")
Annotation Value should bind with a default value or with a config value. try to avoid empty values

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/http/HttpLog.java
> +	@Value("")
Annotation Value should bind with a default value or with a config value. try to avoid empty values

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/http/HttpLog.java
> +public class HttpLog implements IHttpLog {
HttpLog seems to be a POJO, if so remove IHttpLog

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/http/IHttpLog.java
> +package com.github.marocraft.trackntrace.http;
To be removed

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/utils/CommonUtils.java
> +	@Qualifier("logTraceRest")
why is this anotated with a Qualifier

2019-05-17 13:19 UTC, EggIt commented on src/main/java/com/github/marocraft/trackntrace/utils/CommonUtils.java
> +	@Qualifier("logTraceRest")
why is this annotated with Qualifier?

2019-05-17 13:19 UTC, EggIt commented on src/main/resources/application.properties_
> +tnt.logging.format.default={"methodName": "{{methodName}}","className": "{{className}}","logLevel": "{{logLevel}}","executionTime": "{{executionTime}}","logMessage": "{{logMessage}}","traceId": "{{tr
if not used should be removed

2019-05-17 14:29 UTC, housseine commented on src/main/java/com/github/marocraft/trackntrace/build/DefaultLogBuilder.java
> +	@Qualifier("logtraceDefault")
Done

2019-05-21 10:09 UTC, housseine commented on src/main/resources/application.properties_
> +tnt.logging.format.default={"methodName": "{{methodName}}","className": "{{className}}","logLevel": "{{logLevel}}","executionTime": "{{executionTime}}","logMessage": "{{logMessage}}","traceId": "{{tr
done

2019-05-21 10:35 UTC, housseine commented on src/main/java/com/github/marocraft/trackntrace/utils/CommonUtils.java
> +	@Qualifier("logTraceRest")
done

2019-05-21 10:36 UTC, housseine commented on src/main/java/com/github/marocraft/trackntrace/utils/CommonUtils.java
> +	@Qualifier("logTraceRest")
done

2019-05-21 11:48 UTC, housseine commented on src/main/java/com/github/marocraft/trackntrace/http/Correlater.java
> +	@Value(value="")
done

2019-05-21 12:09 UTC, merged